//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compuwreck_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Shipwrecks = new HashSet<Shipwreck>();
        }
    
        public int Event_id { get; set; }
        public string Event1 { get; set; }
        public string Event_Description { get; set; }
    
        public virtual ICollection<Shipwreck> Shipwrecks { get; set; }
    }
}
