//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compuwreck_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int PostId { get; set; }
        public string PageTitle { get; set; }
        public string Body { get; set; }
        public string Image { get; set; }
        public System.DateTime PublishDate { get; set; }
        public System.DateTime UnPublishDate { get; set; }
        public int Type { get; set; }
        public bool Published { get; set; }
    }
}
