//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compuwreck_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Photo_id { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string FileName { get; set; }
        public string URL { get; set; }
        public string Source { get; set; }
        public int Shipwreck_id { get; set; }
    
        public virtual Shipwreck Shipwreck { get; set; }
    }
}
