//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compuwreck_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int ID { get; set; }
        public string AbreviatedTitle { get; set; }
        public string LongTitle { get; set; }
        public string Author { get; set; }
        public string PublisherSource { get; set; }
        public string PublishersAddress { get; set; }
        public string Source { get; set; }
        public string DatePublished { get; set; }
        public string RelevantMaterial { get; set; }
        public string ISBN { get; set; }
    }
}
