//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compuwreck_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipwreck
    {
        public Shipwreck()
        {
            this.Locations = new HashSet<Location>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int Shipwreck_id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Dimensions { get; set; }
        public string Tonnage { get; set; }
        public string Armament { get; set; }
        public Nullable<System.DateTime> DateLost { get; set; }
        public string DateExtn { get; set; }
        public string Locality { get; set; }
        public string PosExtn { get; set; }
        public string Cargo { get; set; }
        public string WindDir { get; set; }
        public string WindForce { get; set; }
        public string References { get; set; }
        public string Remarks { get; set; }
        public string U_Boat { get; set; }
        public Nullable<int> Event_FK { get; set; }
        public Nullable<int> County_FK { get; set; }
    
        public virtual County County { get; set; }
        public virtual Event Event { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
